name: Publish Version

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version type (patch, minor, major)'
        required: true
        default: patch

jobs:
  release:
    name: Publish Version
    runs-on: ubuntu-latest

    steps:
      - name: Configure Git User
        run: |
          git config --global user.email "manmodesanket@gmail.com"
          git config --global user.name "manmodesanket"

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org'

      - name: Clean cache
        run: npm cache clean --force --cache ~/.npm

      - name: Install dependencies
        run: npm ci

      - name: Bump version based on input
        run: npm version ${{ github.event.inputs.version }}

      - name: Build packages
        run: npm run build
        env:
          API_KEY: ${{ secrets.API_KEY }}

      - name: Install updated dependencies (after bump)
        run: npm ci

      - name: Push version bump commit
        run: git push --follow-tags
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to npm (with authentication)
        run: npm publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
